# Generated by Django 5.1.4 on 2025-01-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_name_project_title_project_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
