# Generated by Django 5.1.4 on 2025-01-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_affiliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_urls',
            new_name='image_url',
        ),
    ]
